title: Mecánica elemental
description: Algunas notas sobre física básica
theme: just-the-docs

url: https://ffiza.github.io/mecanica-elemental

aux_links:
  Template Repository: https://github.com/ffiza/mecanica-elemental
