title: Física
description: Algunas notas sobre física básica
theme: just-the-docs

url: https://ffiza.github.io/mecanica-elemental

aux_links:
  Template Repository: https://github.com/ffiza/mecanica-elemental

color_scheme: dark
math: mathjax