title: Física elemental
description: Algunas notas sobre física básica
theme: just-the-docs

url: https://ffiza.github.io/mecanica-elemental

aux_links:
  GitHub: https://github.com/ffiza/mecanica-elemental

aux_links_new_tab: true
color_scheme: dark
math: mathjax